# Generated by Django 4.2.20 on 2025-11-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cusc_edx_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecommerceorder',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecommerceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
    ]
